services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: Mysqlpass@
      MYSQL_DATABASE: coffe_st_db
      MYSQL_USER: coffe_st_user
      MYSQL_PASSWORD: Mysqlpass@

  backend:
    environment:
      APP_NAME: "Coffe St"
      APP_ENV: local
      APP_KEY: base64:XcWQg4VO2wpY9nrf2kkxo4LzcA8FLNjH4JbX3b0nS9E=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      LOG_CHANNEL: stack
      LOG_LEVEL: debug

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: coffe_st_db
      DB_USERNAME: coffe_st_user
      DB_PASSWORD: Mysqlpass@

      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

  frontend:
    environment:
      VITE_API_URL: http://localhost:8000/api
      VITE_APP_NAME: "Coffe St"
